"""engine/vq -- knurlogic's own VQ runtime (design D1).

  vq_switch.py   vqlab's canonical MoE/PLE kernels, VERBATIM (PROVENANCE.md)
  vq_dense.py    vqlab's dense VQLinear/VQEmbedding, VERBATIM -- the three
                 27B rungs and gemma e4b cannot be served without it
  runtime.py     executes the two per knob set, attaches VQ modules (mlx)
  rungs.py       what each released rung shipped, from rungs.json (stdlib)
  rungs.json     per Hub repo: published defaults, knobs, generation,
                 bundle digest, verified -- generated by tools/vq_gate.py

Importing this package imports no mlx; only `runtime` does. The resolver
asks `rungs` for a rung's numerics before anything loads.
"""
from .rungs import knobs, repo_of, rung, verified  # noqa: F401 -- re-exported
